### ISSUE TITLE
Can not reproduce the results of the bohamiann_example notebook

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [automl/pybnn#2]
I tried to reproduce the results of the `bohamiann_example` notebook, but the resulted uncertainty measure is very bad, are the default hyperparameters outdated?

Below are the prediction to the sinc function given by the notebook: 

![image](https://user-images.githubusercontent.com/8230801/54338720-a3808800-466d-11e9-9926-5096f25e4c9e.png)

![image](https://user-images.githubusercontent.com/8230801/54338776-ce6adc00-466d-11e9-858a-39fb8894349c.png)

**Comment by aaronkl** [comment]
Yes, you are right the hyperparameters were a bit outdated. I fixed that.
Thanks!
