### ISSUE TITLE
lr term missing from friction term in SGHMC

### ISSUE THREAD

**Issue by JavierAntoran** [automl/pybnn#4]
Hi,
I might be wrong about this but is there an lr missing in line 93 of https://github.com/automl/pybnn/blob/master/pybnn/sampler/sghmc.py ? When you do momentum.add_(-lr * gradient - mdecay * momentum + sample_t) I think it might need to be momentum.add_(-lr * gradient - lr * mdecay * momentum + sample_t) in order to match the expression in https://arxiv.org/abs/1402.4102  I think including the step size makes sense there as the loss of potential due to friction will depend linearly on the distance travelled.

**Comment by aaronkl** [comment]
I think you are right. Thanks a lot. I will fix it

**Comment by aaronkl** [comment]
I think there is also a mdecay missing in the line above: lr * mdecay * momentum instead of lr *  momentum
