### ISSUE TITLE
DNGO run_mcmc bug report.

### ISSUE THREAD

**Issue by LeonShangguan** [automl/pybnn#8]
When I run DNGO, it cries: `ValueError: too many values to unpack (expected 3)` for `pos, _, _ = self.sampler.run_mcmc(self.p0, self.chain_length, rstate0=self.rng)` in class DNGO, method train. I guess this is because of the update from emcee? Just change `pos, _, _,` to `pos` then it runs well.
I am writing to let you know and perhaps you can check if my method is correct, thanks.

**Comment by aaronkl** [comment]
Thanks for spotting it. Would you mind sending a PR to fix it?

**Comment by arberzela** [comment]
Issue fixed and pushed to master. See this [commit](https://github.com/automl/pybnn/commit/59befe512d6f668f1dfb39ad9ba4c55abc8dd0f6).
